#requires -Version 5.1
[CmdletBinding()]
param(
    [string] $OutputPath,
    [ValidateSet('Utf8Bom', 'Utf8NoBom')]
    [string] $Encoding = 'Utf8Bom',
    [switch] $Check,
    [switch] $Test
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$repositoryRoot = $PSScriptRoot
if (-not $OutputPath) { $OutputPath = Join-Path $repositoryRoot 'VGUIFontChanger.ps1' }
elseif (-not [IO.Path]::IsPathRooted($OutputPath)) { $OutputPath = Join-Path $repositoryRoot $OutputPath }
$OutputPath = [IO.Path]::GetFullPath($OutputPath)
$repositoryPrefix = $repositoryRoot.TrimEnd([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar

$sourceFiles = @(
    'src/bootstrap/Parameters.ps1'
    'src/core/Collections.ps1'
    'src/games/Discovery.ps1'
    'src/vpk/Reader.ps1'
    'src/core/Text.ps1'
    'src/games/SearchPaths.ps1'
    'src/keyvalues/Parser.ps1'
    'src/keyvalues/Document.ps1'
    'src/worker/SchemeParallel.ps1'
    'src/cache/ScanCache.ps1'
    'src/schemes/Resolution.ps1'
    'src/build/SchemeBuild.ps1'
    'src/fonts/Diagnostics.ps1'
    'src/core/Operations.ps1'
    'src/build/Output.ps1'
    'src/settings/Profiles.ps1'
    'src/fonts/Registration.ps1'
    'src/worker/GuiTasks.ps1'
    'src/gui/Preview.ps1'
    'src/gui/Localization.ps1'
    'src/gui/NativeTypes.ps1'
    'src/gui/Dialogs.ps1'
    'src/gui/Controls.ps1'
    'src/gui/Model.ps1'
    'src/gui/ThemeAndLayout.ps1'
    'src/gui/MainWindow.ps1'
    'src/tests/Timer.Tests.ps1'
    'src/tests/SelfTest.ps1'
    'src/tests/Portable.Tests.ps1'
    'src/tests/Hierarchy.Tests.ps1'
    'src/tests/Vpk.Tests.ps1'
    'src/tests/SourceGame.Tests.ps1'
    'src/worker/FunctionManifest.ps1'
    'src/cli/Invoke-CliMode.ps1'
    'src/EntryPoint.ps1'
)

$parts = New-Object 'System.Collections.Generic.List[string]'
$parts.Add("# Generated by Build.ps1 from the files under src/.`n# Edit the source files and rebuild; do not edit this file directly.")
foreach ($relativePath in $sourceFiles) {
    $sourcePath = [IO.Path]::GetFullPath((Join-Path $repositoryRoot $relativePath))
    if (-not $sourcePath.StartsWith($repositoryPrefix, [StringComparison]::OrdinalIgnoreCase)) { throw "Source path escapes the repository: $relativePath" }
    if (-not [IO.File]::Exists($sourcePath)) { throw "Missing source file: $relativePath" }
    $source = [IO.File]::ReadAllText($sourcePath).Replace("`r`n", "`n").Replace("`r", "`n").TrimEnd()
    if ($source) { $parts.Add($source) }
}

$content = (($parts -join "`n`n") + "`n").Replace("`n", "`r`n")
$tokens = $null
$parseErrors = $null
[Management.Automation.Language.Parser]::ParseInput($content, [ref]$tokens, [ref]$parseErrors) | Out-Null
if ($parseErrors.Count) {
    $details = ($parseErrors | ForEach-Object { "line $($_.Extent.StartLineNumber): $($_.Message)" }) -join [Environment]::NewLine
    throw "Generated script failed PowerShell parsing:$([Environment]::NewLine)$details"
}

$utf8 = New-Object Text.UTF8Encoding($Encoding -eq 'Utf8Bom')
$body = $utf8.GetBytes($content)
$preamble = $utf8.GetPreamble()
$expected = New-Object byte[] ($preamble.Length + $body.Length)
[Array]::Copy($preamble, 0, $expected, 0, $preamble.Length)
[Array]::Copy($body, 0, $expected, $preamble.Length, $body.Length)

if ($Check) {
    if (-not [IO.File]::Exists($OutputPath)) { throw "Generated release is missing: $OutputPath" }
    $actual = [IO.File]::ReadAllBytes($OutputPath)
    $matches = $actual.Length -eq $expected.Length
    for ($index = 0; $matches -and $index -lt $actual.Length; $index++) {
        if ($actual[$index] -ne $expected[$index]) { $matches = $false }
    }
    if (-not $matches) { throw 'VGUIFontChanger.ps1 is stale. Run .\Build.ps1 and commit the result.' }
    Write-Host 'Generated release is up to date.'
} else {
    $outputDirectory = Split-Path $OutputPath -Parent
    $null = [IO.Directory]::CreateDirectory($outputDirectory)
    $temporary = Join-Path $outputDirectory ('.vfc-release-' + [Guid]::NewGuid().ToString('N') + '.tmp')
    $backup = Join-Path $outputDirectory ('.vfc-release-' + [Guid]::NewGuid().ToString('N') + '.bak')
    try {
        [IO.File]::WriteAllBytes($temporary, $expected)
        if ([IO.File]::Exists($OutputPath)) { [IO.File]::Replace($temporary, $OutputPath, $backup) }
        else { [IO.File]::Move($temporary, $OutputPath) }
    } finally {
        if ([IO.File]::Exists($temporary)) { [IO.File]::Delete($temporary) }
        if ([IO.File]::Exists($backup)) { [IO.File]::Delete($backup) }
    }
    Write-Host "Generated $OutputPath"
}

if ($Test) {
    $runtimes = @(
        @{Name='Windows PowerShell 5.1';Command='powershell.exe'}
        @{Name='PowerShell 7';Command='pwsh.exe'}
    )
    foreach ($runtime in $runtimes) {
        $command = Get-Command $runtime.Command -ErrorAction SilentlyContinue
        if (-not $command) { throw "$($runtime.Name) is required for the compatibility test." }
        Write-Host "Running self-tests with $($runtime.Name)..."
        & $command.Source -NoProfile -ExecutionPolicy Bypass -File $OutputPath -SelfTest
        if ($LASTEXITCODE -ne 0) { throw "$($runtime.Name) self-test failed with exit code $LASTEXITCODE." }
    }
}
